// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/passage/passage.proto

package passage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PassageServiceClient is the client API for PassageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassageServiceClient interface {
	Passage(ctx context.Context, in *PassageRequest, opts ...grpc.CallOption) (*PassageResponse, error)
}

type passageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassageServiceClient(cc grpc.ClientConnInterface) PassageServiceClient {
	return &passageServiceClient{cc}
}

func (c *passageServiceClient) Passage(ctx context.Context, in *PassageRequest, opts ...grpc.CallOption) (*PassageResponse, error) {
	out := new(PassageResponse)
	err := c.cc.Invoke(ctx, "/PassageService/Passage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassageServiceServer is the server API for PassageService service.
// All implementations must embed UnimplementedPassageServiceServer
// for forward compatibility
type PassageServiceServer interface {
	Passage(context.Context, *PassageRequest) (*PassageResponse, error)
	mustEmbedUnimplementedPassageServiceServer()
}

// UnimplementedPassageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPassageServiceServer struct {
}

func (UnimplementedPassageServiceServer) Passage(context.Context, *PassageRequest) (*PassageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Passage not implemented")
}
func (UnimplementedPassageServiceServer) mustEmbedUnimplementedPassageServiceServer() {}

// UnsafePassageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassageServiceServer will
// result in compilation errors.
type UnsafePassageServiceServer interface {
	mustEmbedUnimplementedPassageServiceServer()
}

func RegisterPassageServiceServer(s grpc.ServiceRegistrar, srv PassageServiceServer) {
	s.RegisterService(&PassageService_ServiceDesc, srv)
}

func _PassageService_Passage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassageServiceServer).Passage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PassageService/Passage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassageServiceServer).Passage(ctx, req.(*PassageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PassageService_ServiceDesc is the grpc.ServiceDesc for PassageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PassageService",
	HandlerType: (*PassageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Passage",
			Handler:    _PassageService_Passage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/passage/passage.proto",
}
